# Generated by Django 3.2.8 on 2021-11-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='message',
            name='room_id',
            field=models.CharField(default='enter', max_length=100000),
            preserve_default=False,
        ),
    ]
